### ISSUE TITLE
Launching the game via launcher.py prevents from using Heavensword and Stormblood content

### ISSUE THREAD

**Issue by ghost** [mclark4386/FF14Launcher#9]
I thought it was strange that A Realm Reborn was displayed as start menu at first, but once I tried to teleport toward a Stormblood location the teleport failed. I can still login with my LVL 70 character and fortunately I was in Limsa Lominsa when I logged out but that's it I'm stuck with A Realm Reborn content if I launch with the custom launcher. I tried launching with the vanilla one of course (but it was in directx9c mode) and it correctly loaded Stormblood content

something worth mentioning is that I purchased the game and DLCs via Steam but I launched the game using the non-steam launcher that apparently works since I do own a ffxiv account on mog station

![image](https://user-images.githubusercontent.com/11262717/40008127-df139cf4-579e-11e8-868e-0f871c7e38f7.png)

**Comment by ghost** [comment]
Apparently I forgot to set the expansion_id in the launcher config!

**Comment by EmperorArthur** [comment]
Glad your issue was resolved.  I really need to re-do the GUI so everything is more clear.
